### ISSUE TITLE
s-mr1 is still used by open devices "repo sync"

### ISSUE THREAD

**Issue by KnuX** [sonyxperiadev/device-sony-murray#20]
Hi,

> $ repo sync
> [...]
> fatal: couldn't find remote ref refs/heads/s-mr1 error: Cannot fetch device-sony-murray from https://github.com/sonyxperiadev/device-sony-murray
> [...]
> error: Cannot checkout device-sony-murray: ManifestInvalidRevisionError: revision s-mr1 in device-sony-murray not found
> error: in `sync`: revision s-mr1 in device-sony-murray not found

So the script fails and we can't go further the legacy guide.

**Comment by jerpelea** [comment]
Hi, 
which Android version are you trying to build ?
Thanks
Alin

**Comment by KnuX** [comment]
Thx for your reply, it's Android 12 (following this guide : https://developer.sony.com/open-source/aosp-on-xperia-open-devices/guides/aosp-build-instructions/build-aosp-android-12-0/)

**Comment by jerpelea** [comment]
The issue has been fixed. Please try again
Best regards
Alin

**Comment by KnuX** [comment]
It works! Thx ^^
