### ISSUE TITLE
bootloop after flashing the build

### ISSUE THREAD

**Issue by protongit** [sonyxperiadev/device-sony-murray#9]
Hi, first of all thank you so much for making clear instructions for AOSP 13 build. I followed exact guidelines as instructed and the compilation process finalized with a successfully build. I flashing the images whithout any error and after reboot the device enter in bootloop. I don´t know where is the error. If you need a debug log, please tell me how. Thanks.

**Comment by jerpelea** [comment]
Hi 
Thanks for the notification
Please use the bugtracker https://github.com/sonyxperiadev/bug_tracker/ for reporting bugs 
can you please provide adb logcat, dmesg or pstore logs
Thanks
Alin
